# Entorno LEMP Basico 
version: '3.8'
services:
  # Contenedor de aplicacion php
  php:
    container_name: SERVER_APP
    hostname: php.local
    build:
      context: ./server/php
    volumes:
      - ./proyecto:/srv/www/api
      - ./server/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./server/php/ini:/usr/local/etc/php/
    env_file: ./server/.env
    restart: unless-stopped
    networks: 
      - net
  # Contenedor Base de Datos
  db:
    container_name: BASE_DATOS
    image: mariadb:latest
    hostname: basedatos.local
    depends_on: 
      - php
    volumes: 
        - ./server/mariadb/db:/var/lib/mysql 
    env_file: ./server/.env
    restart: unless-stopped
    networks: 
        - net 
  # Gestor visual de Base de Datos SOLO POR EL CURSO
  phpmyadmin:
    container_name: GESTOR_BASE_DATOS
    image: phpmyadmin/phpmyadmin:latest
    hostname: phpmyadmin.local
    ports:
      - 8080:80
    depends_on: 
      - db
    volumes: 
        - ./server/php/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        - ./server/php/phpmyadmin/sessions/:/sessions/
    env_file: ./server/.env
    restart: unless-stopped
    networks: 
        - net 
#### <<< Multiples Server Web para Load Balance con Haproxy >>>>>>>        
  # Contenedor Haproxy
  haproxy: 
    container_name: BALANCEADOR
    hostname: haproxy.local
    build: 
      context: ./server/haproxy
    ports:
      - 80:80
    depends_on: 
      - nginx1
      - nginx2
      - nginx3
#    restart: unless-stopped
    networks:
      - net
  #  Grupo de contenedores replicas de Servidor Web
  nginx1: 
    container_name: NGINX_1
    image: nginx:alpine
    hostname: web.local
    ports:
      - 81:80
    volumes:
      - ./proyecto:/srv/www/api
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
    restart: unless-stopped
    networks:
      - net

  nginx2: 
    container_name: NGINX_2
    image: nginx:alpine
    hostname: web.local
    ports:
      - 82:80
    volumes:
      - ./proyecto:/srv/www/api
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
    restart: unless-stopped
    networks:
      - net
 
  nginx3: 
    container_name: NGINX_3
    image: nginx:alpine
    hostname: web.local
    ports:
      - 83:80
    volumes:
      - ./proyecto:/srv/www/api
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
    restart: unless-stopped
    networks:
      - net
networks:
  net: