# Entorno LEMP Basico 
version: '3.8'
services:
  # Contenedor de aplicacion php
  php:
    container_name: SERVER_APP
    image: php:cursophp
    hostname: php.local
    build:
      context: ./server/php
    ports:
      - 9000:9000
    volumes:
      - ./proyecto:/srv/www/api
      - ./server/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    env_file: .env
    restart: on-failure
    networks: 
      - net
  # Contenedor Servidor Web
  nginx: 
    container_name: NGINX
    image: nginx:latest
    hostname: web.local
    ports:
      - 80:80
    volumes:
      - ./proyecto:/srv/www/api
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
    restart: on-failure
    networks:
      - net
  # Contenedor Base de Datos
  db:
    container_name: BASE_DATOS
    image: mariadb:latest
    hostname: basedatos.local
    depends_on: 
      - php
    ports: 
        - 3306:3306
    volumes: 
        - ./server/mariadb/db:/var/lib/mysql 
    env_file: .env
    restart: always
    networks: 
        - net 
networks:
  net: