version: '3.8'
services:
  # Contenedor de aplicacion php
  php:
    container_name: SERVER_APP
    build:
      context: ./server/php
    volumes:
      - ./server/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./server/php/ini/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./proyecto:/srv/www/api
    env_file: ./server/.env
    restart: unless-stopped
    networks: 
      - net
  # Contenedor Base de Datos
  db:
    container_name: BASE_DATOS
    image: mariadb:latest
    hostname: basedatos.local
    depends_on: 
      - php
    volumes: 
        - ./server/mariadb/db:/var/lib/mysql 
    env_file: ./server/.env
    restart: unless-stopped
    networks: 
        - net 
  # Gestor visual de Base de Datos SOLO POR EL CURSO
  phpmyadmin:
    container_name: GESTOR_BASE_DATOS
    image: phpmyadmin/phpmyadmin:latest
    hostname: phpmyadmin.local
    ports:
      - 8080:80
    depends_on: 
      - db
    volumes: 
        - ./server/php/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        - ./server/php/phpmyadmin/sessions/:/sessions/
    env_file: ./server/.env
    restart: unless-stopped
    networks: 
        - net 
  #Contenedor Servidor Web
  nginx: 
    container_name: NGINX
    image: nginx:alpine
    hostname: web.local
    ports: 
      - 80:80
    volumes:
      - ./proyecto:/srv/www/api
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - db
    restart: unless-stopped
    networks:
      - net
networks:
  net: